In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

In [2]:
df = pd.read_csv("C:\\Users\\sanja\\Downloads\\100-days-of-machine-learning-main\\day36-imputing-numerical-data\\titanic_toy.csv")

In [3]:
df.head()

Age     Fare  Family  Survived
0  22.0   7.2500       1         0
1  38.0  71.2833       1         1
2  26.0   7.9250       0         1
3  35.0  53.1000       1         1
4  35.0   8.0500       0         0

In [4]:
df.isnull().mean()

Age         0.198653
Fare        0.050505
Family      0.000000
Survived    0.000000
dtype: float64

In [5]:
x = df.drop(columns=['Survived'])
y= df['Survived']

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [7]:
x_train.shape, x_test.shape

((712, 3), (179, 3))

In [8]:
x_train.isnull().mean()

Age       0.207865
Fare      0.050562
Family    0.000000
dtype: float64

In [9]:
mean_age = x_train['Age'].mean()
median_age = x_train['Age'].median()

mean_fare = x_train['Fare'].mean()
median_fare = x_train['Fare'].median()

In [10]:
x_train['Age_median'] = x_train['Age'].fillna(median_age)
x_train['Age_mean'] = x_train['Age'].fillna(mean_age)

x_train['Fare_median'] = x_train['Fare'].fillna(median_fare)
x_train['fare_mean'] = x_train['Fare'].fillna(mean_fare)

In [14]:
x_train.sample(7)

Age      Fare  Family  Age_median   Age_mean  Fare_median   fare_mean
429  32.0       NaN       0       32.00  32.000000      14.4583   32.617597
111  14.5   14.4542       1       14.50  14.500000      14.4542   14.454200
478  22.0    7.5208       0       22.00  22.000000       7.5208    7.520800
256   NaN   79.2000       0       28.75  29.785904      79.2000   79.200000
150  51.0   12.5250       0       51.00  51.000000      12.5250   12.525000
334   NaN  133.6500       1       28.75  29.785904     133.6500  133.650000
440  45.0   26.2500       2       45.00  45.000000      26.2500   26.250000

In [15]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [16]:
imputer1 = SimpleImputer(strategy='median')
imputer2 = SimpleImputer(strategy='mean')

In [17]:
trf = ColumnTransformer([
    ('imputer1',imputer1,['Age']),
    ('imputer2',imputer2,['Fare'])
],remainder='passthrough')

In [18]:
trf.fit(X_train)

ColumnTransformer(remainder='passthrough',
                  transformers=[('imputer1', SimpleImputer(strategy='median'),
                                 ['Age']),
                                ('imputer2', SimpleImputer(), ['Fare'])])

In [19]:
trf.named_transformers_['imputer1'].statistics_

array([28.75])

In [20]:
trf.named_transformers_['imputer2'].statistics_

array([32.61759689])

In [21]:
X_train = trf.transform(X_train)
X_test = trf.transform(X_test)

In [22]:
X_train

array([[ 40.    ,  27.7208,   0.    ],
       [  4.    ,  16.7   ,   2.    ],
       [ 47.    ,   9.    ,   0.    ],
       ...,
       [ 71.    ,  49.5042,   0.    ],
       [ 28.75  , 221.7792,   0.    ],
       [ 28.75  ,  25.925 ,   0.    ]])