In [1]:
import numpy as np

In [2]:
a = np.random.randint(1,100,15)
a

array([16, 21, 51, 44, 73, 89, 36, 76, 72, 54, 19, 82, 71, 74, 50])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[49,  1, 82, 64],
       [14, 38, 28, 95],
       [38, 53, 38, 21],
       [72, 47, 51, 32],
       [ 7, 14,  2, 13],
       [28, 84, 60, 56]])

In [4]:
np.sort(a)

array([16, 19, 21, 36, 44, 50, 51, 54, 71, 72, 73, 74, 76, 82, 89])

In [8]:
np.sort(a)[::-1]

array([89, 82, 76, 74, 73, 72, 71, 54, 51, 50, 44, 36, 21, 19, 16])

In [5]:
np.sort(b)

array([[ 1, 49, 64, 82],
       [14, 28, 38, 95],
       [21, 38, 38, 53],
       [32, 47, 51, 72],
       [ 2,  7, 13, 14],
       [28, 56, 60, 84]])

In [6]:
np.sort(b,axis=0)

array([[ 7,  1,  2, 13],
       [14, 14, 28, 21],
       [28, 38, 38, 32],
       [38, 47, 51, 56],
       [49, 53, 60, 64],
       [72, 84, 82, 95]])

In [9]:
np.append(a,199)

array([ 16,  21,  51,  44,  73,  89,  36,  76,  72,  54,  19,  82,  71,
        74,  50, 199])

In [10]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[49.,  1., 82., 64.,  1.],
       [14., 38., 28., 95.,  1.],
       [38., 53., 38., 21.,  1.],
       [72., 47., 51., 32.,  1.],
       [ 7., 14.,  2., 13.,  1.],
       [28., 84., 60., 56.,  1.]])

In [12]:
np.where(a>50)

(array([ 2,  4,  5,  7,  8,  9, 11, 12, 13], dtype=int64),)

In [13]:
np.where(a>50,0,a)

array([16, 21,  0, 44,  0,  0, 36,  0,  0,  0, 19,  0,  0,  0, 50])

In [14]:
np.argmax(a)

5

In [15]:
np.argmin(a)

0

In [16]:
np.cumsum(a)

array([ 16,  37,  88, 132, 205, 294, 330, 406, 478, 532, 551, 633, 704,
       778, 828])

In [18]:
np.cumprod(a)

array([         16,         336,       17136,      753984,    55040832,
         603666752,   257166592, -1930175488, -1533681664, -1214431232,
       -1599356928,  1996718080,    33062912, -1848311808,  2073690112])

In [19]:
np.percentile(a,75)

73.5

In [20]:
items = [23,3,9,23,4]
np.isin(a,items)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])